name: Build and test
on:
  - pull_request
  - workflow_dispatch
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build_and_test:
    name: Build and test
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: temurin
          cache: gradle
      - name: Build and test
        id: build_and_test
        run: ./gradlew --no-daemon javadoc test
      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: ./build/test-results/test/*.xml
