name: Mark release
on:
  push:
    branches:
      - master
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  mark_release:
    name: Mark release if appropriate
    permissions:
      checks: write
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: temurin
          cache: gradle
      - uses: gradle/actions/setup-gradle@v3
      - name: Build and test
        run: ./gradlew test
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          comment_mode: off
          files: ./**/build/test-results/test/*.xml
      - uses: mooltiverse/nyx-github-action@main
        with:
          command: mark
          releasePrefix: "v_"
