name: Semantic release
on:
  push:
    branches:
      - master
jobs:
  semantic_release:
    name: Semantic release
    permissions:
      checks: write
      contents: write
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: temurin
          cache: gradle
      - uses: gradle/actions/setup-gradle@v3
      - name: Build and test
        run: ./gradlew test
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          comment_mode: off
          files: ./**/build/test-results/test/*.xml
      - uses: paulhatch/semantic-version@5.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_prefix: v_
